import os
import re
from pathlib import Path

from config import (
    CPP_EXTENSIONS,
    PYTHON_EXTENSIONS,
    MYSQL_EXTENSIONS,
    CPP_FOLDER,
    PYTHON_FOLDER,
    MYSQL_FOLDER,
    EASY,
    MEDIUM,
    HARD,
)


def detect_language(problem_folder: Path):
    """
    Detect solution language based on file extension.
    Returns:
        (language_name, solution_file_path)
    """

    for file in problem_folder.iterdir():

        if not file.is_file():
            continue

        suffix = file.suffix.lower()

        if suffix in CPP_EXTENSIONS:
            return CPP_FOLDER, file

        if suffix in PYTHON_EXTENSIONS:
            return PYTHON_FOLDER, file

        if suffix in MYSQL_EXTENSIONS:
            return MYSQL_FOLDER, file

    return None, None


def detect_difficulty(problem_folder: Path):
    """
    Reads README.md generated by LeetHub
    Returns:
        Easy / Medium / Hard
    """

    readme = problem_folder / "README.md"

    if not readme.exists():
        return "Unknown"

    try:
        text = readme.read_text(encoding="utf-8").lower()

        if "easy" in text:
            return EASY

        if "medium" in text:
            return MEDIUM

        if "hard" in text:
            return HARD

    except Exception:
        pass

    return "Unknown"


def get_problem_name(problem_folder: Path):
    """
    Returns folder name
    Example:
        0001-two-sum
    """

    return problem_folder.name


def is_problem_folder(folder: Path):
    """
    Checks whether folder is a LeetCode problem folder.

    Example:
        0001-two-sum
        3731-find-missing-elements
    """

    if not folder.is_dir():
        return False

    return bool(re.match(r"^\d+[-_].*", folder.name))


def parse_problem(problem_folder: Path):
    """
    Parses complete information of one problem.
    """

    language, solution = detect_language(problem_folder)

    difficulty = detect_difficulty(problem_folder)

    return {
        "name": get_problem_name(problem_folder),
        "language": language,
        "difficulty": difficulty,
        "solution": solution,
        "readme": problem_folder / "README.md",
    }


if __name__ == "__main__":

    repo = Path(input("Repository Path : "))

    for folder in repo.iterdir():

        if not is_problem_folder(folder):
            continue

        info = parse_problem(folder)

        print("=" * 50)
        print(info["name"])
        print("Language :", info["language"])
        print("Difficulty :", info["difficulty"])
        print("Solution :", info["solution"])